# -*- coding: utf-8 -*-
"""publish_mqtt_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1APROb2s2C7bWnJsW-b8S_dgmAD3bB9MD
"""

pip install paho-mqtt

import paho.mqtt.client as mqtt
import time

config_data = {
    "Lidar detection score":"7.2",
    "Lidar detection zones":"360",
    "location":{
        "r":"1.56565",
        "theta":"88.418556"
    }
}

mqtt_pub_topic = "mqtt/testweat"
client = mqtt.Client()

def on_connect(client, userdata, flags, rc):
  client.connected_flag = True
  client.disconnect_flag = False
  print("Connected")
  print("rc: " + str(rc))

def on_publish(client, userdata, mid):
  print("mid: "+ str(mid))

def on_disconnect(client, userdata, rc):
  print("disconnecting reason " +str(rc))
  client.disconnect_flag = True
  client.connected_flag = False
  client.loop_stop()

def on_message(client, userdata, message):
  message_received = json.loads(message.payload)
  print("message received: ", message_received)

def init_mqtt(client, mqtt_host, mqtt_port, mqtt_uid, mqtt_password):
  mqtt.Client.connected_flag = False
  #client.username_pw_set(username = mqtt_uid, password = mqtt_password)
  client.on_connect = on_connect
  client.on_disconnect = on_disconnect
  client.on_publish = on_publish
  client.connect(mqtt_host, int(mqtt_port))
  #client.subscribe(mqtt_topic)
  client.loop_start()
  while not client.connected_flag: #wait in loop
    print("In wait loop")
    time.sleep(1)
  #return 0

def handler():
  mqtt_host="test.mosquitto.org"
  mqtt_port="1883"
  mqtt_uid="haps"
  mqtt_password="haps"
  #connection initiated
  init_mqtt(client, mqtt_host, mqtt_port, mqtt_uid, mqtt_password)
  while client.connected_flag:
    client.publish(str(mqtt_pub_topic), str(config_data))
    print(config_data)
    time.sleep(1)

if __name__ == "__main__":
  handler()